title: Eco Albert
logo: /assets/img/poto cv.png
description: Hey there! I'm Eco Albert,
description2: Student At Design Communication Visual At Universitas Prima Indonesia
show_downloads: true
theme: jekyll-theme-minimal
